---
# Zielsysteme. Die Gruppe heisst bewusst "webservers"
# -> passend zu group_vars/webservers.yml.
all:
  children:
    webservers:
      hosts:
        target01:
          ansible_host: 10.10.10.106
        target02:
          ansible_host: 10.10.10.107
